oper_dingding_robot: # 运营管理组机器人
  url: https://oapi.dingtalk.com/robot/send?access_token=736ec8464250f0c7e9d766350dbf5f6975e2cec2c9b1cfd4db372d9dd8bfe0ba
hotal_dingding_robot: # 酒店组机器人
  url: https://oapi.dingtalk.com/robot/send?access_token=555d6a81bd2d47a67dff9fa80e50919ec749a2b2028590706de73cb2f087cd85
plat_dingding_robot: # 平台应用组机器人
  url: https://oapi.dingtalk.com/robot/send?access_token=9c9637bbe3d3f4da5a296ff84ca3d9efb427aa526642faee0160b2eff315f4ec
flight_dingding_robot: # 机票组机器人
  url: https://oapi.dingtalk.com/robot/send?access_token=86bc8b327b563c65f4a05ebd22a39c395138ca10fd8ea4b0b8a3ff66194cf996
error_data_robot: # 异常订单通知机器人
  url: https://oapi.dingtalk.com/robot/send?access_token=5bcfbb8531d6ebfff22ed3a742ffa73ae3534aa56fcd6f5fd317338d27f38257
xingao_account_config_check: # 新奥结算通知机器人
  url: https://oapi.dingtalk.com/robot/send?access_token=b82db0e1fe4417487f1181836664800373c8ee45985b24cb8aa803c135250562